name : Deploy to testing env ut_next_dev
on:
  push:
    branches: [ development ]

jobs:
  first:
    name: Pull from github
    runs-on: ubuntu-latest
    steps:
    - name: deploy dev https://ut-staging.bgskr-project.my.id/
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_KRIS }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.MY_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd ${{ secrets.DIR_STG }}
          git pull origin development
